services:

  db:
    image: postgres:17.5
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realdb
    ports:
      - "5435:5432" # проброс наружу (можно убрать, если не нужно подключение с хоста)
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: my_fastapi
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "8001:8000"

volumes:
  pg_data: